version: '3.4'

networks:
  dev:
  test:

x-base-app: &base_app
  image: app:latest
  build: .
  volumes:
    - './app:/app/app'
  command: bin/spring server

x-db-vars: &db-vars
  DATABASE_HOST: db
  DATABASE_USERNAME: postgres
x-base-db: &base_db
  image: postgres


services:
  dev:
    <<: *base_app
    ports:
      - '3000:3000'
    environment:
      <<: *db-vars
    depends_on:
      - dev_db
    networks:
      dev:
        aliases:
          - app

  dev_db:
    <<: *base_db
    ports:
      - '5432:5432'
    volumes:
      - dev_db_data:/var/lib/postgresql/data
    networks:
      dev:
        aliases:
          - db

  test:
    <<: *base_app
    depends_on:
      - test_db
    environment:
      <<: *db-vars
      NODE_ENV: test
    networks:
      test:
        aliases:
          - app
  test_db:
    <<: *base_db
    ports:
      - '5433:5432'
    volumes:
      - test_db_data:/var/lib/postgresql/data
    networks:
      test:
        aliases:
          - db

volumes:
  test_db_data:
  dev_db_data:
